// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _QUERY_RESPONSE.proto

package com.q.prot_packet;

public final class QueryResponsePacket {
  private QueryResponsePacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _QUERY_RESPONSEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet._QUERY_RESPONSE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 code = 1 [default = 6];</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1 [default = 6];</code>
     */
    int getCode();

    /**
     * <code>optional string object_data = 3;</code>
     */
    boolean hasObjectData();
    /**
     * <code>optional string object_data = 3;</code>
     */
    java.lang.String getObjectData();
    /**
     * <code>optional string object_data = 3;</code>
     */
    com.google.protobuf.ByteString
        getObjectDataBytes();
  }
  /**
   * Protobuf type {@code packet._QUERY_RESPONSE}
   */
  public  static final class _QUERY_RESPONSE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet._QUERY_RESPONSE)
      _QUERY_RESPONSEOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use _QUERY_RESPONSE.newBuilder() to construct.
    private _QUERY_RESPONSE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _QUERY_RESPONSE() {
      code_ = 6;
      objectData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private _QUERY_RESPONSE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              objectData_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.q.prot_packet.QueryResponsePacket.internal_static_packet__QUERY_RESPONSE_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.q.prot_packet.QueryResponsePacket.internal_static_packet__QUERY_RESPONSE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.class, com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1 [default = 6];</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1 [default = 6];</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int OBJECT_DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object objectData_;
    /**
     * <code>optional string object_data = 3;</code>
     */
    public boolean hasObjectData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string object_data = 3;</code>
     */
    public java.lang.String getObjectData() {
      java.lang.Object ref = objectData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objectData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string object_data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getObjectDataBytes() {
      java.lang.Object ref = objectData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, objectData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, objectData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE)) {
        return super.equals(obj);
      }
      com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE other = (com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE) obj;

      boolean result = true;
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && (hasObjectData() == other.hasObjectData());
      if (hasObjectData()) {
        result = result && getObjectData()
            .equals(other.getObjectData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasObjectData()) {
        hash = (37 * hash) + OBJECT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getObjectData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet._QUERY_RESPONSE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet._QUERY_RESPONSE)
        com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.q.prot_packet.QueryResponsePacket.internal_static_packet__QUERY_RESPONSE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.q.prot_packet.QueryResponsePacket.internal_static_packet__QUERY_RESPONSE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.class, com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.Builder.class);
      }

      // Construct using com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 6;
        bitField0_ = (bitField0_ & ~0x00000001);
        objectData_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.q.prot_packet.QueryResponsePacket.internal_static_packet__QUERY_RESPONSE_descriptor;
      }

      public com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE getDefaultInstanceForType() {
        return com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.getDefaultInstance();
      }

      public com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE build() {
        com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE buildPartial() {
        com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE result = new com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.objectData_ = objectData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE) {
          return mergeFrom((com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE other) {
        if (other == com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasObjectData()) {
          bitField0_ |= 0x00000002;
          objectData_ = other.objectData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ = 6;
      /**
       * <code>required int32 code = 1 [default = 6];</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1 [default = 6];</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1 [default = 6];</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1 [default = 6];</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 6;
        onChanged();
        return this;
      }

      private java.lang.Object objectData_ = "";
      /**
       * <code>optional string object_data = 3;</code>
       */
      public boolean hasObjectData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string object_data = 3;</code>
       */
      public java.lang.String getObjectData() {
        java.lang.Object ref = objectData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            objectData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string object_data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getObjectDataBytes() {
        java.lang.Object ref = objectData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string object_data = 3;</code>
       */
      public Builder setObjectData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        objectData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string object_data = 3;</code>
       */
      public Builder clearObjectData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        objectData_ = getDefaultInstance().getObjectData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string object_data = 3;</code>
       */
      public Builder setObjectDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        objectData_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet._QUERY_RESPONSE)
    }

    // @@protoc_insertion_point(class_scope:packet._QUERY_RESPONSE)
    private static final com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE();
    }

    public static com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<_QUERY_RESPONSE>
        PARSER = new com.google.protobuf.AbstractParser<_QUERY_RESPONSE>() {
      public _QUERY_RESPONSE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _QUERY_RESPONSE(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_QUERY_RESPONSE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_QUERY_RESPONSE> getParserForType() {
      return PARSER;
    }

    public com.q.prot_packet.QueryResponsePacket._QUERY_RESPONSE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet__QUERY_RESPONSE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet__QUERY_RESPONSE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025_QUERY_RESPONSE.proto\022\006packet\"7\n\017_QUER" +
      "Y_RESPONSE\022\017\n\004code\030\001 \002(\005:\0016\022\023\n\013object_da" +
      "ta\030\003 \001(\tB(\n\021com.q.prot_packetB\023QueryResp" +
      "onsePacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_packet__QUERY_RESPONSE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet__QUERY_RESPONSE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet__QUERY_RESPONSE_descriptor,
        new java.lang.String[] { "Code", "ObjectData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
