// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _OPERATION_CPP.proto

#ifndef PROTOBUF__5fOPERATION_5fCPP_2eproto__INCLUDED
#define PROTOBUF__5fOPERATION_5fCPP_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf__5fOPERATION_5fCPP_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaults_OPEARATIONImpl();
void InitDefaults_OPEARATION();
inline void InitDefaults() {
  InitDefaults_OPEARATION();
}
}  // namespace protobuf__5fOPERATION_5fCPP_2eproto
namespace packet {
class _OPEARATION;
class _OPEARATIONDefaultTypeInternal;
extern _OPEARATIONDefaultTypeInternal __OPEARATION_default_instance_;
}  // namespace packet
namespace packet {

// ===================================================================

class _OPEARATION : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet._OPEARATION) */ {
 public:
  _OPEARATION();
  virtual ~_OPEARATION();

  _OPEARATION(const _OPEARATION& from);

  inline _OPEARATION& operator=(const _OPEARATION& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  _OPEARATION(_OPEARATION&& from) noexcept
    : _OPEARATION() {
    *this = ::std::move(from);
  }

  inline _OPEARATION& operator=(_OPEARATION&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const _OPEARATION& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const _OPEARATION* internal_default_instance() {
    return reinterpret_cast<const _OPEARATION*>(
               &__OPEARATION_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(_OPEARATION* other);
  friend void swap(_OPEARATION& a, _OPEARATION& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline _OPEARATION* New() const PROTOBUF_FINAL { return New(NULL); }

  _OPEARATION* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const _OPEARATION& from);
  void MergeFrom(const _OPEARATION& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(_OPEARATION* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 session_id = 2;
  bool has_session_id() const;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 2;
  ::google::protobuf::int32 session_id() const;
  void set_session_id(::google::protobuf::int32 value);

  // optional int32 operation_description = 3;
  bool has_operation_description() const;
  void clear_operation_description();
  static const int kOperationDescriptionFieldNumber = 3;
  ::google::protobuf::int32 operation_description() const;
  void set_operation_description(::google::protobuf::int32 value);

  // optional int32 operational_local_id = 4;
  bool has_operational_local_id() const;
  void clear_operational_local_id();
  static const int kOperationalLocalIdFieldNumber = 4;
  ::google::protobuf::int32 operational_local_id() const;
  void set_operational_local_id(::google::protobuf::int32 value);

  // required int32 code = 1 [default = 2];
  bool has_code() const;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:packet._OPEARATION)
 private:
  void set_has_code();
  void clear_has_code();
  void set_has_session_id();
  void clear_has_session_id();
  void set_has_operation_description();
  void clear_has_operation_description();
  void set_has_operational_local_id();
  void clear_has_operational_local_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 session_id_;
  ::google::protobuf::int32 operation_description_;
  ::google::protobuf::int32 operational_local_id_;
  ::google::protobuf::int32 code_;
  friend struct ::protobuf__5fOPERATION_5fCPP_2eproto::TableStruct;
  friend void ::protobuf__5fOPERATION_5fCPP_2eproto::InitDefaults_OPEARATIONImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// _OPEARATION

// required int32 code = 1 [default = 2];
inline bool _OPEARATION::has_code() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void _OPEARATION::set_has_code() {
  _has_bits_[0] |= 0x00000008u;
}
inline void _OPEARATION::clear_has_code() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void _OPEARATION::clear_code() {
  code_ = 2;
  clear_has_code();
}
inline ::google::protobuf::int32 _OPEARATION::code() const {
  // @@protoc_insertion_point(field_get:packet._OPEARATION.code)
  return code_;
}
inline void _OPEARATION::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:packet._OPEARATION.code)
}

// required int32 session_id = 2;
inline bool _OPEARATION::has_session_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void _OPEARATION::set_has_session_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void _OPEARATION::clear_has_session_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void _OPEARATION::clear_session_id() {
  session_id_ = 0;
  clear_has_session_id();
}
inline ::google::protobuf::int32 _OPEARATION::session_id() const {
  // @@protoc_insertion_point(field_get:packet._OPEARATION.session_id)
  return session_id_;
}
inline void _OPEARATION::set_session_id(::google::protobuf::int32 value) {
  set_has_session_id();
  session_id_ = value;
  // @@protoc_insertion_point(field_set:packet._OPEARATION.session_id)
}

// optional int32 operation_description = 3;
inline bool _OPEARATION::has_operation_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void _OPEARATION::set_has_operation_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void _OPEARATION::clear_has_operation_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void _OPEARATION::clear_operation_description() {
  operation_description_ = 0;
  clear_has_operation_description();
}
inline ::google::protobuf::int32 _OPEARATION::operation_description() const {
  // @@protoc_insertion_point(field_get:packet._OPEARATION.operation_description)
  return operation_description_;
}
inline void _OPEARATION::set_operation_description(::google::protobuf::int32 value) {
  set_has_operation_description();
  operation_description_ = value;
  // @@protoc_insertion_point(field_set:packet._OPEARATION.operation_description)
}

// optional int32 operational_local_id = 4;
inline bool _OPEARATION::has_operational_local_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void _OPEARATION::set_has_operational_local_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void _OPEARATION::clear_has_operational_local_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void _OPEARATION::clear_operational_local_id() {
  operational_local_id_ = 0;
  clear_has_operational_local_id();
}
inline ::google::protobuf::int32 _OPEARATION::operational_local_id() const {
  // @@protoc_insertion_point(field_get:packet._OPEARATION.operational_local_id)
  return operational_local_id_;
}
inline void _OPEARATION::set_operational_local_id(::google::protobuf::int32 value) {
  set_has_operational_local_id();
  operational_local_id_ = value;
  // @@protoc_insertion_point(field_set:packet._OPEARATION.operational_local_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace packet

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF__5fOPERATION_5fCPP_2eproto__INCLUDED
