// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _QUERY_RESPONSE_CPP.proto

#ifndef PROTOBUF__5fQUERY_5fRESPONSE_5fCPP_2eproto__INCLUDED
#define PROTOBUF__5fQUERY_5fRESPONSE_5fCPP_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaults_QUERY_RESPONSEImpl();
void InitDefaults_QUERY_RESPONSE();
inline void InitDefaults() {
  InitDefaults_QUERY_RESPONSE();
}
}  // namespace protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto
namespace packet {
class _QUERY_RESPONSE;
class _QUERY_RESPONSEDefaultTypeInternal;
extern _QUERY_RESPONSEDefaultTypeInternal __QUERY_RESPONSE_default_instance_;
}  // namespace packet
namespace packet {

// ===================================================================

class _QUERY_RESPONSE : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet._QUERY_RESPONSE) */ {
 public:
  _QUERY_RESPONSE();
  virtual ~_QUERY_RESPONSE();

  _QUERY_RESPONSE(const _QUERY_RESPONSE& from);

  inline _QUERY_RESPONSE& operator=(const _QUERY_RESPONSE& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  _QUERY_RESPONSE(_QUERY_RESPONSE&& from) noexcept
    : _QUERY_RESPONSE() {
    *this = ::std::move(from);
  }

  inline _QUERY_RESPONSE& operator=(_QUERY_RESPONSE&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const _QUERY_RESPONSE& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const _QUERY_RESPONSE* internal_default_instance() {
    return reinterpret_cast<const _QUERY_RESPONSE*>(
               &__QUERY_RESPONSE_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(_QUERY_RESPONSE* other);
  friend void swap(_QUERY_RESPONSE& a, _QUERY_RESPONSE& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline _QUERY_RESPONSE* New() const PROTOBUF_FINAL { return New(NULL); }

  _QUERY_RESPONSE* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const _QUERY_RESPONSE& from);
  void MergeFrom(const _QUERY_RESPONSE& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(_QUERY_RESPONSE* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string object_data = 3;
  bool has_object_data() const;
  void clear_object_data();
  static const int kObjectDataFieldNumber = 3;
  const ::std::string& object_data() const;
  void set_object_data(const ::std::string& value);
  #if LANG_CXX11
  void set_object_data(::std::string&& value);
  #endif
  void set_object_data(const char* value);
  void set_object_data(const char* value, size_t size);
  ::std::string* mutable_object_data();
  ::std::string* release_object_data();
  void set_allocated_object_data(::std::string* object_data);

  // required int32 code = 1 [default = 6];
  bool has_code() const;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:packet._QUERY_RESPONSE)
 private:
  void set_has_code();
  void clear_has_code();
  void set_has_object_data();
  void clear_has_object_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr object_data_;
  ::google::protobuf::int32 code_;
  friend struct ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::TableStruct;
  friend void ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::InitDefaults_QUERY_RESPONSEImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// _QUERY_RESPONSE

// required int32 code = 1 [default = 6];
inline bool _QUERY_RESPONSE::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void _QUERY_RESPONSE::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void _QUERY_RESPONSE::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void _QUERY_RESPONSE::clear_code() {
  code_ = 6;
  clear_has_code();
}
inline ::google::protobuf::int32 _QUERY_RESPONSE::code() const {
  // @@protoc_insertion_point(field_get:packet._QUERY_RESPONSE.code)
  return code_;
}
inline void _QUERY_RESPONSE::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:packet._QUERY_RESPONSE.code)
}

// optional string object_data = 3;
inline bool _QUERY_RESPONSE::has_object_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void _QUERY_RESPONSE::set_has_object_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void _QUERY_RESPONSE::clear_has_object_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void _QUERY_RESPONSE::clear_object_data() {
  object_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_object_data();
}
inline const ::std::string& _QUERY_RESPONSE::object_data() const {
  // @@protoc_insertion_point(field_get:packet._QUERY_RESPONSE.object_data)
  return object_data_.GetNoArena();
}
inline void _QUERY_RESPONSE::set_object_data(const ::std::string& value) {
  set_has_object_data();
  object_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet._QUERY_RESPONSE.object_data)
}
#if LANG_CXX11
inline void _QUERY_RESPONSE::set_object_data(::std::string&& value) {
  set_has_object_data();
  object_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:packet._QUERY_RESPONSE.object_data)
}
#endif
inline void _QUERY_RESPONSE::set_object_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_object_data();
  object_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet._QUERY_RESPONSE.object_data)
}
inline void _QUERY_RESPONSE::set_object_data(const char* value, size_t size) {
  set_has_object_data();
  object_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet._QUERY_RESPONSE.object_data)
}
inline ::std::string* _QUERY_RESPONSE::mutable_object_data() {
  set_has_object_data();
  // @@protoc_insertion_point(field_mutable:packet._QUERY_RESPONSE.object_data)
  return object_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* _QUERY_RESPONSE::release_object_data() {
  // @@protoc_insertion_point(field_release:packet._QUERY_RESPONSE.object_data)
  clear_has_object_data();
  return object_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void _QUERY_RESPONSE::set_allocated_object_data(::std::string* object_data) {
  if (object_data != NULL) {
    set_has_object_data();
  } else {
    clear_has_object_data();
  }
  object_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), object_data);
  // @@protoc_insertion_point(field_set_allocated:packet._QUERY_RESPONSE.object_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace packet

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF__5fQUERY_5fRESPONSE_5fCPP_2eproto__INCLUDED
