// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _QUERY_RESPONSE_CPP.proto

#include "_QUERY_RESPONSE_CPP.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace packet {
class _QUERY_RESPONSEDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<_QUERY_RESPONSE>
      _instance;
} __QUERY_RESPONSE_default_instance_;
}  // namespace packet
namespace protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto {
void InitDefaults_QUERY_RESPONSEImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::packet::__QUERY_RESPONSE_default_instance_;
    new (ptr) ::packet::_QUERY_RESPONSE();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::packet::_QUERY_RESPONSE::InitAsDefaultInstance();
}

void InitDefaults_QUERY_RESPONSE() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaults_QUERY_RESPONSEImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::packet::_QUERY_RESPONSE, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::packet::_QUERY_RESPONSE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::packet::_QUERY_RESPONSE, code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::packet::_QUERY_RESPONSE, object_data_),
  1,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::packet::_QUERY_RESPONSE)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::packet::__QUERY_RESPONSE_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "_QUERY_RESPONSE_CPP.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031_QUERY_RESPONSE_CPP.proto\022\006packet\"7\n\017_"
      "QUERY_RESPONSE\022\017\n\004code\030\001 \002(\005:\0016\022\023\n\013objec"
      "t_data\030\003 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "_QUERY_RESPONSE_CPP.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto
namespace packet {

// ===================================================================

void _QUERY_RESPONSE::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int _QUERY_RESPONSE::kCodeFieldNumber;
const int _QUERY_RESPONSE::kObjectDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

_QUERY_RESPONSE::_QUERY_RESPONSE()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::InitDefaults_QUERY_RESPONSE();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet._QUERY_RESPONSE)
}
_QUERY_RESPONSE::_QUERY_RESPONSE(const _QUERY_RESPONSE& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  object_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_object_data()) {
    object_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.object_data_);
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:packet._QUERY_RESPONSE)
}

void _QUERY_RESPONSE::SharedCtor() {
  _cached_size_ = 0;
  object_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 6;
}

_QUERY_RESPONSE::~_QUERY_RESPONSE() {
  // @@protoc_insertion_point(destructor:packet._QUERY_RESPONSE)
  SharedDtor();
}

void _QUERY_RESPONSE::SharedDtor() {
  object_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void _QUERY_RESPONSE::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* _QUERY_RESPONSE::descriptor() {
  ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const _QUERY_RESPONSE& _QUERY_RESPONSE::default_instance() {
  ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::InitDefaults_QUERY_RESPONSE();
  return *internal_default_instance();
}

_QUERY_RESPONSE* _QUERY_RESPONSE::New(::google::protobuf::Arena* arena) const {
  _QUERY_RESPONSE* n = new _QUERY_RESPONSE;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void _QUERY_RESPONSE::Clear() {
// @@protoc_insertion_point(message_clear_start:packet._QUERY_RESPONSE)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!object_data_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*object_data_.UnsafeRawStringPointer())->clear();
    }
    code_ = 6;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool _QUERY_RESPONSE::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet._QUERY_RESPONSE)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 code = 1 [default = 6];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_code();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string object_data = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_object_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->object_data().data(), static_cast<int>(this->object_data().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "packet._QUERY_RESPONSE.object_data");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet._QUERY_RESPONSE)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet._QUERY_RESPONSE)
  return false;
#undef DO_
}

void _QUERY_RESPONSE::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet._QUERY_RESPONSE)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 code = 1 [default = 6];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // optional string object_data = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->object_data().data(), static_cast<int>(this->object_data().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "packet._QUERY_RESPONSE.object_data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->object_data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:packet._QUERY_RESPONSE)
}

::google::protobuf::uint8* _QUERY_RESPONSE::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:packet._QUERY_RESPONSE)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 code = 1 [default = 6];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // optional string object_data = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->object_data().data(), static_cast<int>(this->object_data().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "packet._QUERY_RESPONSE.object_data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->object_data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet._QUERY_RESPONSE)
  return target;
}

size_t _QUERY_RESPONSE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet._QUERY_RESPONSE)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 code = 1 [default = 6];
  if (has_code()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }
  // optional string object_data = 3;
  if (has_object_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->object_data());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void _QUERY_RESPONSE::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet._QUERY_RESPONSE)
  GOOGLE_DCHECK_NE(&from, this);
  const _QUERY_RESPONSE* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const _QUERY_RESPONSE>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet._QUERY_RESPONSE)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet._QUERY_RESPONSE)
    MergeFrom(*source);
  }
}

void _QUERY_RESPONSE::MergeFrom(const _QUERY_RESPONSE& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet._QUERY_RESPONSE)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_object_data();
      object_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.object_data_);
    }
    if (cached_has_bits & 0x00000002u) {
      code_ = from.code_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void _QUERY_RESPONSE::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet._QUERY_RESPONSE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void _QUERY_RESPONSE::CopyFrom(const _QUERY_RESPONSE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet._QUERY_RESPONSE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool _QUERY_RESPONSE::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void _QUERY_RESPONSE::Swap(_QUERY_RESPONSE* other) {
  if (other == this) return;
  InternalSwap(other);
}
void _QUERY_RESPONSE::InternalSwap(_QUERY_RESPONSE* other) {
  using std::swap;
  object_data_.Swap(&other->object_data_);
  swap(code_, other->code_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata _QUERY_RESPONSE::GetMetadata() const {
  protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf__5fQUERY_5fRESPONSE_5fCPP_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace packet

// @@protoc_insertion_point(global_scope)
