source=Glob('src/*.cpp')
libs=['pthread', 'ssl', 'crypto', 'protobuf', 'pqxx', 'pq']
lib_paths=''
env=Environment(CPPPATH='src/',
		CXXFLAGS="-std=c++14")
env.Program('bin/Server', source, LIBS=libs)
